import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { WithLayout } from '../components/layout/Layout'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        Hi
    </div>
  )
}

export default WithLayout(Home)
